name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Trivy Scan"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Helm Charts
        uses: actions/checkout@v3
        with:
          repository: Maiz2k2/springboot-helm
          path: helm
          token: ${{ secrets.GIT_TOKEN }}

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Configure kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name springboot-cluster --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          helm upgrade --install hello-world ./helm/hello-world \
            --set image.repository=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/springboot-app/springboot-cicd \
            --set image.tag=latest \
            --set imagePullSecrets[0].name=ecr-secret
