name: SonarQube Scan

on:
  workflow_run:
    workflows: ["Build and Upload Artifact"]
    types:
      - completed

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full commit history for SonarCloud

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.8.6'

      - name: Download Artifact from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p target
          aws s3 cp s3://springboot-task-artifacts/artifacts/hello-world-1.0-SNAPSHOT.jar target/hello-world-1.0-SNAPSHOT.jar

      - name: Verify downloaded artifact
        run: ls -l target/

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify sonar:sonar \
            -Dsonar.organization=maiz2k2 \
            -Dsonar.projectKey=springboot-cicd \
            -Dsonar.host.url=https://sonarcloud.io
