name: SonarQube Scan

on:
  workflow_run:
    workflows: ["Build and Upload Artifact"]
    types:
      - completed

jobs:
  sonar-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean verify sonar:sonar \                          
           -Dsonar.organization=maiz2k2 \                                                                                   
           -Dsonar.projectKey=springboot-cicd \
           -Dsonar.host.url=https://sonarcloud.io \
           -Dsonar.login=de5743fe18da2896d9b66df6c301f781babfcc0f

#####
