name: Scan with Trivy

on:
  workflow_run:
    workflows: ["Dockerize and Push to ECR"]
    types:
      - completed

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Ensure Docker is Installed
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker not found! Installing..."
            sudo apt-get update
            sudo apt-get install -y docker.io
          else
            echo "Docker is already installed."
          fi
          docker --version

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Pull Docker Image
        run: |
          docker pull 975050045168.dkr.ecr.us-east-1.amazonaws.com/springboot-app/springboot-cicd:latest

      - name: Check if Trivy is Installed
        id: check-trivy
        run: |
          if command -v trivy &> /dev/null; then
            echo "Trivy is already installed."
            echo "trivy_installed=true" >> $GITHUB_ENV
          else
            echo "Trivy is not installed."
            echo "trivy_installed=false" >> $GITHUB_ENV
          fi

      - name: Install Trivy (Official Method)
        if: env.trivy_installed == 'false'
        run: |
          sudo apt-get install -y wget gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy
          trivy --version

      - name: Run Trivy Image Scan
        run: |
          trivy image ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/springboot-app/springboot-cicd:latest --exit-code 1 --severity HIGH,CRITICAL
